# PostgreSQL
quarkus.datasource.jdbc.url=${POSTGRES_URL}
quarkus.datasource.username=${POSTGRES_USER}
quarkus.datasource.password=${POSTGRES_PASSWORD}

# Hibernate
quarkus.hibernate-orm.schema-management.strategy=${HIBERNATE_ORM_SCHEMA_MANAGEMENT_STRATEGY}
