# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/testdb
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres

# Hibernate
quarkus.hibernate-orm.schema-management.strategy=update
quarkus.hibernate-orm.log.sql=true

quarkus.http.root-path=/api

# Swagger
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger

# OpenAPI
quarkus.smallrye-openapi.path=/openapi
quarkus.smallrye-openapi.info-title=Clients Management API
quarkus.smallrye-openapi.info-description=RESTful service for managing clients - Prueba Técnica para Desarrollador Back-end

# Dev
%dev.quarkus.datasource.dev-ui.allow-sql=true

# Jackson
quarkus.jackson.fail-on-unknown-properties=false

